apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
  namespace: app-prod
data:
  ASPNETCORE_ENVIRONMENT: "Production"

  # RabbitMQ
  RabbitMq__Host: "rabbitmq"
  RabbitMq__Port: "5672"
  RabbitMq__VirtualHost: "/"
