apiVersion: v1
kind: Secret
metadata:
  name: secret-api
  namespace: app-prod
type: Opaque
stringData:
  RabbitMq__User: guest
  RabbitMq__Password: guest

  ConnectionStrings__DefaultConnection: "Server=mssql;Database=AppDb;User ID=sa;Password=huaHhbSyjn9bttt;TrustServerCertificate=true;"
